version: '3.8'

services:
  app:
    build: .
    container_name: telegram-summarizer-app
    ports:
      # Map the container's internal port (defined by PORT or default 8080) to host port 8080
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      # Pass environment variables from .env file
      - PYTHONUNBUFFERED=1 # Ensures logs are shown immediately
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
      - WEBHOOK_SECRET_TOKEN=${WEBHOOK_SECRET_TOKEN}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      # - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN} # Keep if needed elsewhere
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
      - PORT=${PORT:-8080} # Port for the FastAPI app
      # - CRAWL4AI_URL=http://crawl4ai:8000 # Removed - library is used directly
    volumes:
      - .:/app # Mount the current directory into /app in the container
    # depends_on: # Removed
    #   - crawl4ai # Removed
    networks: # Keep network if other services need it, otherwise can be removed
      - summarizer-net 

# Removed the crawl4ai service block
# networks:
#   summarizer-net:
#     driver: bridge

# Define the network if app still needs it (e.g., for potential future services)
# If no other services will be added, the network block can be removed entirely.
networks:
  summarizer-net:
    driver: bridge
